### PR TITLE
feat: run tests in parallel

### PR DESCRIPTION
**Pull request by panteo**
**Add support for parallel testing.**

This pull request adds support for parallel testing by creating a separate Playwright user data directory for each worker. This prevents the workers from interfering with each other and allows them to run independently.

It reads the worker index from `process.env.TEST_WORKER_INDEX` like stated [here](https://playwright.dev/docs/test-parallel#worker-index-and-parallel-index).

### PR Checklist

- [x] I have run linter locally
- [x] I have run unit and integration tests locally
  - [x] Update configuration the newest version (readme and const)
- [x] Rebased to master branch / merged master

### CODE REVIEW

**Comment by osis** [comment]
@panteo this is a very cool PR! Let me get to some house cleaning items and I'll come back to this to validate. This solves a very real use case for the library. Excited to get it merged.

**Comment by panteo** [comment]
Great, thank you!

Il sab 21 ott 2023, 20:56 Dwayne Forde ***@***.***> ha
scritto:

**Comment by osis** [comment]
This looks good. If you give it a rebase off the latest changes (should be clean), this will be good to go. Thank again!

**Comment by panteo** [comment]
I'll do it tomorrow.

I'm really excited for my first contribution to an open source project.

😀


Il dom 22 ott 2023, 07:21 Dwayne Forde ***@***.***> ha
scritto:

**Comment by panteo** [comment]
@osis done! :muscle:

**Review by osis — APPROVED** [review]

**Pull request merged**
