### PR TITLE
feat: 🎸 add new param for another extensions

### LINKED ISSUE #292: Add other extensions to dappwright bootstrap
**Is your feature request related to a problem? Please describe.**
Need to install few another extensions for test.

**Describe the solution you'd like**
Add new options parameter to `dappwright.bootstrap`

### PR DESCRIPTION
**Pull request by IGoRFonin**
**Short description of work done**
Add new parameter `additionalExtensions` for `dappwright.bootstrap`

- [x] I have run linter locally
- [x] I have run unit and integration tests locally
- [x] Rebased to master branch / merged master

### Issues
Reslove #292 

Closes #292

### CODE REVIEW

**Comment by osis** [comment]
Hey @IGoRFonin! This is a really interesting contribution. How do you see this playing out with other extensions? All of the actions would need to be adjusted to the UI for that extension, so I'm curious.

**Comment by IGoRFonin** [comment]
@osis Hi.
I use it for "webtc control" to hide my ip when I use a proxy, there is more info there https://browserleaks.com/webrtc. I do this because chromium doesn't have it out of the box.

Example:
image

chromium i use from `playwright-extra` with extra features to block bot detection.

**Comment by osis** [comment]
ah I see. Thanks for clarifying. Sounds like a great usecase. Other thing I would like to clarify in the interface that these are `additionalExtensions` or `otherExtensions` since the wallet is an extension itself and installing multiple can cause issues.

**Comment by IGoRFonin** [comment]
Change parameter name.

**Review by osis — APPROVED** [review]

**Comment by osis** [comment]
Thanks for the contribution! 🥳

**Pull request merged**
